[package]
name = "eml_types"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
eml_diagnostics.workspace = true
eml_hir.workspace = true
la-arena.workspace = true

[dev-dependencies]
eml_test_support = { workspace = true, features = ["types"] }
eml_syntax.workspace = true
insta.workspace = true
