[package]
name = "eml_hir"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
eml_diagnostics.workspace = true
eml_syntax.workspace = true
la-arena.workspace = true

[dev-dependencies]
eml_test_support = { workspace = true, features = ["hir"] }
insta.workspace = true
