[package]
name = "eml_core_ir"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
eml_hir.workspace = true
eml_types.workspace = true
la-arena.workspace = true

[dev-dependencies]
eml_diagnostics.workspace = true
eml_syntax.workspace = true
eml_test_support = { workspace = true, features = ["core"] }
insta.workspace = true
